### ISSUE TITLE
Crash on Delete Game Profile

### ISSUE THREAD

**Issue by giacogiac** [Denellyne/PCXSense#10]
The software crashes when you click Delete profile on a Game Profile that is currently in use.

To reproduce :
create a new Game profile
Set application name to "PCXSense"
Delete the profile

**Comment by Denellyne** [comment]
Does it happen when you set the app bame to anyting else?

**Comment by giacogiac** [comment]
No I wasn't able to reproduce with another name

**Comment by Denellyne** [comment]
@giacogiac I'll check what's up with that later today

**Comment by Denellyne** [comment]
@giacogiac I'm not able to reproduce this bug
