### ISSUE TITLE
Built in game profiles are used instead of custom one

### ISSUE THREAD

**Issue by Butterscotch96** [Denellyne/PCXSense#16]
**Describe the bug**
I don't like the built in Cemu profile so I want to change it. Works fine when tested on other apps but Cemu still uses the built in one.

**To Reproduce**
1. Make new profile
2. Set name to Cemu
3. Cemu uses the built in one still.

**Expected behavior**
It should use my custom profile.

**Comment by Denellyne** [comment]
Fixed on the newest update. https://github.com/Denellyne/PCXSense/releases/tag/Latest
