### ISSUE TITLE
Forza Horizon 5 Rally Adventure L2 R2 adaptive triggers not working the force function in dualsense pad

### ISSUE THREAD

**Issue by Nick7257** [Denellyne/PCXSense#18]
Greetings. In this game, the adaptive triggers act as the default throttle and brake. And they work in the game, but they cannot be connected to the force function, that is, they are always pressed very lightly. Even if you create a profile for this game and include Rigid in it, for example. Then the buttons X, Y, A, B will stop working for no clear reason.

**Comment by Denellyne** [comment]
If the game supports the dualsense nativaly then you can't do much ,unless you can change the controller your using inside the game to a XInput controller

**Comment by Nick7257** [comment]
It's clear. This game out of the box will probably only support the Xbox controller, it's a shame that PCXSense can't customize the triggers. Although the DualSenseX | DS5 Windows can do this correctly, but it is not convenient to use due to a lot of unnecessary vibrations, whether appropriate or not.
PCXSense is more convenient for me to use. In any case, thanks for answering.
