### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [Denellyne/PCXSense#3]
trying to unzip the rar file but its not showing any exe, its in the zip but its extracting. any way you can provide?

**Comment by Denellyne** [comment]
Is it being detected as a virus?

**Comment by Denellyne** [comment]
@Xx-Mohit-xX Try seeing if the new release works for you and tell me something afterwards

**Comment by Denellyne** [comment]
Given the user didn't answer in 1 week and it seems to be an issue exclusive to this user Im going to close,if you need anything else @Xx-Mohit-xX just open another issue ;D
