### ISSUE TITLE
I cant start it

### ISSUE THREAD

**Issue by le1111er** [Denellyne/PCXSense#4]
i'v unzipped the package, after that click the pcxsense.exe but no response, just the cursor with loading for a moment

**Comment by Denellyne** [comment]
Whitelist it on your antivirus and try again, I'm having problems my app getting flagged as a virus because of the antivirus, Im working on solving it right now.
If it still doesn't work try the version without the updater , if that doens't solve send another message and I'll try to help you the best I can.

**Comment by deaniswho** [comment]
Hello i have the same problem but theres a little black windows with some code that quickly opens for one second and is then gone. after that nothing happens.

**Comment by Denellyne** [comment]
@deaniswho Which version are you using?

**Comment by deaniswho** [comment]
> @deaniswho Which version are you using? The window with some code is probably the autoupdater which if your still using it,Its bugged and its removed since last update

the newest 0.5 also tried the 0.4 but both dont work always the same black windows with code that opens for a second. 0.4 loaded a bit longer tho but still after that nothing happens.

**Comment by Denellyne** [comment]
@deaniswho Are you able to record a video of you opening the app so I can see?
If not is this screen the one that opens by any chance? 
![image](https://github.com/Denellyne/PCXSense/assets/56112881/cffe445a-cd54-4ed9-baf3-9a730702f4f2)

**Comment by deaniswho** [comment]
> @deaniswho Are you able to record a video of you opening the app so I can see? If not is this screen the one that opens by any chance? ![image](https://private-user-images.githubusercontent.com/56112881/298593570-cffe445a-cd54-4ed9-baf3-9a730702f4f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Mjg4NjUsIm5iZiI6MTcwNTkyODU2NSwicGF0aCI6Ii81NjExMjg4MS8yOTg1OTM1NzAtY2ZmZTQ0NWEtY2Q1NC00ZWQ5LWJhZjMtOWE3MzA3MDJmNGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEzMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MWE2ODgwZTY0ZGE1NjNiOGI5MzZmYmYzZTZlY2EzYzM0ODkyMTllOTljNTk3YmM1ZGM2N2I2NTlmZjdjOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Coay_rNtIipP_Hj51KbaQ7SOtkaSgufFzfqxrj9V9Os)

yeah thats exactly it!

**Comment by Denellyne** [comment]
Ok that's the Update Checker,so dw about it. Can you send me a screenshot of your PCXSense folder?

**Comment by deaniswho** [comment]
> Ok that's the Update Checker,so dw about it. Can you send me a screenshot of your PCXSense folder? Also check that no instance of PCXSense is open in task manager and try to whitelist it on your antivirus

![Screenshot 2024-01-22 140931](https://github.com/Denellyne/PCXSense/assets/141984135/66176f91-1a0d-462b-bd6d-e3782413ce45)

**Comment by deaniswho** [comment]
> Ok that's the Update Checker,so dw about it. Can you send me a screenshot of your PCXSense folder? Also check that no instance of PCXSense is open in task manager and try to whitelist it on your antivirus

i also deactivated the entire windows real time protection just to be sure

**Comment by Denellyne** [comment]
If you have multiple monitors unplug all of em execpt one and try to open;
Try open it as Admin;
If that doesn't work I'll send you a version with a few checks that will dump where the error happend.

**Comment by deaniswho** [comment]
> If you have multiple monitors unplug all of em execpt one and try to open; Try open it as Admin; If that doesn't work I'll send you a version with a few checks that will dump where the error happend.

only one monitor and i already tried running as admin sadly no differnce. please send me that version thank you!

**Comment by Denellyne** [comment]
Yup I know the problem then , you need to install this https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe

I forgot to put a check to see if the user has this installed ,Its my fault and I will fix for the next version,Install that and try opening it and tell me if its fixed

**Comment by deaniswho** [comment]
> Yup I know the problem then , you need to install this https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe
> 
> I forgot to put a check to see if the user has this installed ,Its my fault and I will fix for the next version,Install that and try opening it and tell me if its fixed

and boom it works thank you so much!

**Comment by Denellyne** [comment]
yup... I skill issued myself so hard right now hahaha.

**Comment by deaniswho** [comment]
> yup... I skill issued myself so hard right now hahaha.

this was all just a test to make the next version even better

**Comment by Denellyne** [comment]
Understandable I wouldn't trust myself with a computer either tbf

**Comment by le1111er** [comment]
> Whitelist it on your antivirus and try again, I'm having problems my app getting flagged as a virus because of the antivirus, Im working on solving it right now. If it still doesn't work try the version without the updater , if that doens't solve send another message and I'll try to help you the best I can.

I've already use the version without updater, it works like what I said, and I have checked the processes but no such process like PSXSense

**Comment by Denellyne** [comment]
@le1111er Have you installed VIgem? https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe

**Comment by le1111er** [comment]
> @le1111er Have you installed VIgem? https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe

Maybe you can add this to the package?

**Comment by Denellyne** [comment]
I've added a check ,it will be on the next release but did it fix it?

**Comment by le1111er** [comment]
> I've added a check ,it will be on the next release but did it fix it?

Yes, it works, thank you for your help

**Comment by Denellyne** [comment]
You're welcome !!
