### ISSUE TITLE
Wont start, freaks out

### ISSUE THREAD

**Issue by user18081972** [Denellyne/PCXSense#5]
https://github.com/Denellyne/PCXSense/assets/124319511/585f78e0-ea14-45da-8e04-276558764c53

this happens when i start the program. its kinda hard to close once this starts happening.

**Comment by Denellyne** [comment]
Download the version without the updater
https://github.com/Denellyne/PCXSense/releases/download/Latest/PCXSenseNoUpdater.rar

**Comment by Denellyne** [comment]
I've decided I'll remove the autoupdater given the hassle its giving me and just warn the user about a new update and redirect them to the download page,thanks for the feedback!!
