### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by AftDawn** [Denellyne/PCXSense#7]
Hi, will PCXSense have a Linux build sometime in the future? Or is that out of scope for this project?

**Comment by Denellyne** [comment]
I don't believe is out of scope but for now I'm focusing on the windows build because I'm not experienced with linux but I will probably get around to it as a means to learn Linux

**Comment by DrKoneko** [comment]
Would also love to see this

**Comment by kiven7e** [comment]
im working on something similar and found this [github repo](https://github.com/nowrep/dualsensectl). it might be useful to figure out how the controller is controlled on linux.

**Comment by Denellyne** [comment]
Thank you,,I have recently started using Linux ,specially when I'm developing so thanks!!
