### ISSUE TITLE
Dualsense Edge support?

### ISSUE THREAD

**Issue by GittyUser54321** [Denellyne/PCXSense#8]
Would be good to have support like on Ps5 which saves the profiles to the DS Edge. 

Also, even better if you could do custom curves like on DS4 but save it to the profile (memory) of DS Edge. At the moment, the edge only has predefined response curves that can be slightly adjusted.

**Comment by Denellyne** [comment]
I don't know what you mean by custom curves and I don't own a DS Edge ,its really expensive so I'm sorry but it's out of scope of this project
