### ISSUE TITLE
Controller hangs/freezes, disconnect/reconnect doesn't work but restarting pcxsense does

### ISSUE THREAD

**Issue by Azalea224** [Denellyne/PCXSense#9]
**Describe the bug**
Controller hangs/freezes, disconnect/reconnect doesn't work but restarting pcxsense does.
Happens to me when playing both wired and wireless, dualsense controller.
Even the graphical interface is not updating with the controller inputs but I can still click on the controller settings and misc context windows (changing controller settings does not affect the controller at all.)
Haven't had the time to test other games but it happens with Granblue Fantasy Relink,
**To Reproduce**
Unsure, seems to happen at random.

**Comment by Azalea224** [comment]
tried to locate any console logs, I do not know where/if Beta 0.7 even logs.
additional information would be that I did not run into this issue in Beta 0.6.

**Comment by Denellyne** [comment]
There's no console logs, I'm not able to do a through read through the code right now ,but i'll upload a build in my GDrive with O2 optimizations to see if that's the problem

**Comment by Denellyne** [comment]
https://drive.google.com/file/d/1X1uJo842nMTJqXXRQafw8BhsuPvxcZum/view?usp=sharing

Try to see if this one stops working,I'm aware of the bug I just haven't been able to figure out why it happens.

**Comment by Denellyne** [comment]
https://drive.google.com/file/d/1UBSL1LTXAVNTxDp-hpTOw-g0wdYEFyYF/view?usp=sharing

Try to see if this one stops working,I'm aware of the bug I just haven't been able to figure out why it happens.
If it stops working again go to the Debug Menu (on misc and see if the values of the joysticks are changing please)
@Azalea224

**Comment by Azalea224** [comment]
I just got it set up, I'll let you know if the bug occurs again

**Comment by Denellyne** [comment]
> I just got it set up, I'll let you know if the bug occurs again

Im Expecting it to occur again ,my theory is that because of the new way that i'm doing the input read and writes of the controller,whenever you open a app that writes to the controller it's overriding my apps permissions ,because as far as I remember it still shows the battery level and says its connected,this also happend to me btw but I did not run into this while in USB only bluetooth...

**Comment by Denellyne** [comment]
@Azalea224 https://drive.google.com/file/d/1Fu9iUooj9v1rUBI1Fr_qFmNeO295-fHK/view?usp=sharing
This version has a reconnect button,try using this version instead,before pressing the reconnect button if it stops working,check the Debug Menu and see if its reading the joystick inputs

**Comment by Azalea224** [comment]
the values of the joysticks do not change when it freezes, the reconnect button causes a program crash, I see two and I haven't tried the second one yet

**Comment by Denellyne** [comment]
> the values of the joysticks do not change when it freezes, the reconnect button causes a program crash, I see two and I haven't tried the second one yet
> 

Aight try the second button then

**Comment by Denellyne** [comment]
> got lucky and got another freeze just now, other reconnect crashes

Try again the reconnect when it crashes,its bugges but sometimes it doesnt crash

**Comment by Azalea224** [comment]
the program becomes not responding and I waited 60+ seconds and it still wasn't responding

**Comment by Denellyne** [comment]
I think i figured it out... im not able rightnow to compile a new build but in an hour i will

**Comment by Azalea224** [comment]
okay, sure tyt! the good work is really appreciated ^^

**Comment by Azalea224** [comment]
so far so good, had just 2s of it randomly freezing in 3 hours. no full lock yet

**Comment by Denellyne** [comment]
> so far so good, had just 2s of it randomly freezing in 3 hours. no full lock yet

NICE,though im still not sure its totally fixed so i'm not gonna close this yet

**Comment by Azalea224** [comment]
issue happened again today with the latest version you've sent in this issue. program goes completely not responding using both reconnect buttons.

**Comment by Denellyne** [comment]
Ill be home today so I can finally debug this properly,thanks for your help tho

**Comment by Denellyne** [comment]
Issue seems to be solved ,it will be applied on next release.
